const questionSets = {
  "Quiz Tamyiz Kolom 1": [
    { latin: "dengan", arab: "بِ" },
    { latin: "seperti", arab: "كَ" },
    { latin: "untuk", arab: "لِ" },
    { latin: "untuk", arab: "لَ" },
    { latin: "kepada", arab: "اِلَى" },
    { latin: "di atas", arab: "عَلَى" },
    { latin: "dari", arab: "مِنْ" },
    { latin: "di dalam", arab: "فِى" },
    { latin: "dari", arab: "عَنْ" },
    { latin: "hingga", arab: "حَتَّى" },

  ],

  "Quiz Tamyiz Kolom 2-5": [
    { latin: "wahai", arab: "يَا" },
    { latin: "kecuali", arab: "اِلَّا" },
    { latin: "tidak ada", arab: "لَا" },
    { latin: "sesungguhnya", arab: "اِنَّ" },
    { latin: "sesungguhnya", arab: "اَنَّ" },
    { latin: "seakan", arab: "كَأَنَّ" },
    { latin: "tetapi", arab: "لٰكِنَّ" },
    { latin: "semoga", arab: "لَعَلَّ" },
    { latin: "andaikan", arab: "لَيْتَ" },
  ],
  "Quiz Tamyiz Kolom 6-7": [
    { latin: "adalah", arab: "كَانَ" },
    { latin: "tiada", arab: "لَيْسَ" },
    { latin: "hendaknya", arab: "اَنْ" },
    { latin: "tidak akan", arab: "لَنْ" },
    { latin: "kalau demikian", arab: "اِذَنْ" },
    { latin: "supaya", arab: "كَيْ" },
    { latin: "supaya", arab: "لِ" },
    { latin: "hingga", arab: "حَتّٰى" },
  ],
  "Quiz Tamyiz Kolom 8-10": [
    { latin: "janganlah", arab: "لَا" },
    { latin: "tidak", arab: "لَمْ" },
    { latin: "tidak", arab: "لَمَّا" },
    { latin: "hendaklah", arab: "لِ" },
    { latin: "hendaklah", arab: "وَلْ" },
    { latin: "hendaklah", arab: "فَلْ" },
    { latin: "jika", arab: "اِنْ" },
    { latin: "siapa", arab: "مَنْ" },
    { latin: "apa", arab: "مَا" },
    { latin: "kemanapun", arab: "اَيْنَمَا" },
    { latin: "dimanapun", arab: "حَيْثُمَا" },
    { latin: "bagaimanapun", arab: "مَهْمَا" },
  ],
  "Quiz Tamyiz Kolom 11-12": [
    { latin: "kecuali", arab: "اِلَّا" },
    { latin: "hendaklah jangan", arab: "اَلَّا" },
    { latin: "sekali-kali jangan", arab: "كَلَّا" },
    { latin: "wahai", arab: "يَا" },
    { latin: "wahai", arab: "يَااَيُّهَا" },
    { latin: "wahai", arab: "يَااَيَّتُهاَ" },
  ],
  "Quiz Tamyiz Kolom 13": [
    { latin: "dan", arab: "وَ" },
    { latin: "atau", arab: "اَوْ" },
    { latin: "maka", arab: "فَ" },
    { latin: "atau", arab: "اَمْ" },
    { latin: "adapun", arab: "اَمَّا" },
    { latin: "kemudian", arab: "ثُمَّ" },
    { latin: "bahkan", arab: "بَلْ" },
    { latin: "sehingga", arab: "حَتّٰى" },
    { latin: "akan tetapi", arab: "لٰكِنْ" },
  ],
  "Quiz Tamyiz Kolom 14-17": [
    { latin: "sungguh", arab: "لَ" },
    { latin: "sungguh", arab: "قَدْ" },
    { latin: "sungguh", arab: "لَقَدَْ" },
    { latin: "akan", arab: "سَ" },
    { latin: "akan", arab: "سَوْفَ" },
    { latin: "bukan", arab: "مَا" },
    { latin: "bukan", arab: "لَا" },
    { latin: "sebaik-baik", arab: "نِعْمَ" },
    { latin: "sejelek-jelek", arab: "بِـئْسَ" },
  ],
  "Quiz Tamyiz Kolom 18": [
    { latin: "jika", arab: "اِذْ" },
    { latin: "jika", arab: "اِذَا" },
    { latin: "jika", arab: "اِذَنْ" },
    { latin: "jika tidak", arab: "اِمَّا" },
    { latin: "adapun", arab: "اَمَّا" },
    { latin: "ketika", arab: "لَمَّا" },
    { latin: "walaupun", arab: "لَوْ" },
    { latin: "mengapa tidak", arab: "لَوْلَا" },
    { latin: "mengapa tidak", arab: "لَوْمَا" },
  ],
  "Quiz Tamyiz Kolom 19": [
    { latin: "apakah", arab: "اَ" },
    { latin: "ingatlah", arab: "اَلَا" },
    { latin: "siapakah", arab: "اَيُّ" },
    { latin: "di mana", arab: "اَيْنَ" },
    { latin: "apakah", arab: "مَا" },
    { latin: "siapakah", arab: "مَنْ" },
    { latin: "kapan", arab: "مَتٰى" },
    { latin: "berapa", arab: "كَمْ" },
    { latin: "bagaimana", arab: "كَيفَ" },
    { latin: "apakah", arab: "هَلْ" },
    { latin: "apakah", arab: "مَاذَا" },
    { latin: "mengapa", arab: "لِمَا" },
    { latin: "mengapa", arab: "لِمَاذَا" },
  ],
  "Quiz Tamyiz Kolom 20": [
    { latin: "sebelum", arab: "قَبْلَ" },
    { latin: "sesudah", arab: "بَعْدَ" },
    { latin: "selain", arab: "غَيْرَ" },
    { latin: "selain", arab: "دُوْنَ" },
    { latin: "di depan", arab: "اَمَامَ" },
    { latin: "di belakang", arab: "وَرَاءَ" },
    { latin: "di belakang", arab: "خَلْفَ" },
    { latin: "di atas", arab: "فَوْقَ" },
    { latin: "di bawah", arab: "تَحْتَ" },
    { latin: "di samping", arab: "جَانِبَ" },
    { latin: "di sekitar", arab: "حَوْلَ" },
    { latin: "setiap", arab: "كُلَّ" },
    { latin: "beserta", arab: "مَعَ" },
    { latin: "di sisi", arab: "عِنْدَ" },
    { latin: "di antara", arab: "بَيْنَ" },
  ],
  "Quiz Tamyiz Kolom 21": [
    { latin: "yang", arab: "اَلّـَذي" },
    { latin: "yang", arab: "اَلّـَذانِ" },
    { latin: "orang2 yang", arab: "اَلّـَذيْنَ" },
    { latin: "yang", arab: "اَلّـَتِي" },
    { latin: "yang", arab: "اَلّـَتَانِ" },
    { latin: "orang2 yang", arab: "اَلّاَتِي" },
    { latin: "orang2 yang", arab: "اَلّاَئِي" },
    { latin: "apa yang", arab: "مَا" },
    { latin: "siapa yang", arab: "مَنْ" },
  ],
  "Quiz Tamyiz Kolom 22-23": [
    { latin: "itu (👨)", arab: "ذٰلِكَ" },
    { latin: "itu (👨👨)", arab: "ذٰلِكُمَا" },
    { latin: "itu (banyak)", arab: "ذٰلِكُمْ" },
    { latin: "itu (👩)", arab: "تِلْكَ" },
    { latin: "itu (👩👩)", arab: "تِلْكُمَا" },
    { latin: "itu (banyak)", arab: "تِلْكُمْ" },
    { latin: "mereka itu", arab: "اُولٓئِكَ" },
    { latin: "ini (👨)", arab: "هٰذَا" },
    { latin: "ini (👨👨)", arab: "هٰذَانِ" },
    { latin: "mereka ini", arab: "هٰؤُلٓاءِ" },
    { latin: "ini (👩)", arab: "هٰذِهِ" },
    { latin: "ini (👩👩)", arab: "هٰتَانِ" },
  ],
  "Quiz Tamyiz Kolom 24": [
    { latin: "dia (L1)", arab: "هُوَ" },
    { latin: "dia (L2)", arab: "(L2)هُمَا" },
    { latin: "mereka (L)", arab: "هُمْ" },
    { latin: "dia (P1)", arab: "هِيَ" },
    { latin: "dia (P2)", arab: "(P2)هُمَا" },
    { latin: "mereka (P)", arab: "هُنَّ" },
    { latin: "kamu (L1)", arab: "اَنْتَ" },
    { latin: "kamu (L2)", arab: "(L2)اَنْـتُمَا" },
    { latin: "Kalian (L)", arab: "اَنْـتُمْ" },
    { latin: "kamu (P1)", arab: "اَنْتِ" },
    { latin: "kamu (P2)", arab: "(P2)اَنْـتُمَا" },
    { latin: "kalian (P)", arab: "اَنْـتُنَّ" },
    { latin: "saya", arab: "اَنَا" },
    { latin: "kami", arab: "نَحْنُ" },
  ],
  "Quiz Tamyiz Kolom 25": [
    { latin: "dia (L1)", arab: "هُ/هِ" },
    { latin: "dia (L2)", arab: "(L2)هُمَا/هِمَا" },
    { latin: "mereka (L)", arab: "هُمْ/هِمْ" },
    { latin: "dia (P1)", arab: "هَا" },
    { latin: "dia (P2)", arab: "(P2)هُمَا/هِمَا" },
    { latin: "mereka (P)", arab: "هُنَّ/هِنَّ" },
    { latin: "kamu (L1)", arab: "كَ" },
    { latin: "kamu (L2)", arab: "(L2)كُمَا" },
    { latin: "Kalian (L)", arab: "كُمْ" },
    { latin: "kamu (P1)", arab: "كِ" },
    { latin: "kamu (P2)", arab: "(P2)كُمَا" },
    { latin: "kalian (P)", arab: "كُنَّ" },
    { latin: "saya", arab: "ـيْ/ـيَ/نِى" },
    { latin: "kami", arab: "نَا" },
  ],
  "Quiz Tamyiz Kolom 26": [
    { latin: "hanya kepadanya (L1)", arab: "اِيَّاهُ" },
    { latin: "hanya kepadanya (L2)", arab: "(L2)اِيَّاهُمَا" },
    { latin: "hanya kepada mereka (L)", arab: "اِيَّاهُمْ" },
    { latin: "hanya kepadanya (P1)", arab: "اِيَّاهَا" },
    { latin: "hanya kepadanya (P2)", arab: "(P2)اِيَّاهُمَا" },
    { latin: "hanya kepada mereka (P)", arab: "اِيَّاهُنَّ" },
    { latin: "hanya kepadamu (L1)", arab: "اِيَّاكَ" },
    { latin: "hanya kepadamu (L2)", arab: "(L2)اِيَّاكُمَا" },
    { latin: "hanya kepada kalian (L)", arab: "اِيَّاكُمْ" },
    { latin: "hanya kepadamu (P1)", arab: "اِيَّاكِ" },
    { latin: "hanya kepadamu (P2)", arab: "(P2)اِيَّاكُمَا" },
    { latin: "hanya kepada kalian (P)", arab: "اِيَّاكُنَّ" },
    { latin: "hanya kepada saya", arab: "اِيَّايَ" },
    { latin: "hanya kepada kami", arab: "اِيَّانَا" },
  ],
};
